export const opacityZero = "opacity: 0";
export const opacityOne = "opacity: 1";
export const leftSlideHundred = `${opacityZero};
transform: translateX(100%);`;
export const leftSlideZero = `${opacityOne};
transform: translateX(0%);`;
export const rightSlideZero = `${opacityZero};
transform: translateX(-100%);`;
export const rightSlideHundred = `${opacityOne};
transform: translateX(0%);`;
export const topSlideZero = `${opacityZero};
transform: translateY(-100%);`;
export const topSlideHundred = `${opacityOne};
transform: translateY(0%);`;
export const bottomSlideZero = `${opacityZero};
transform: translateY(100%);
`;
export const bottomSlideHundred = `${opacityOne};
transform: translateY(0%);`;
